name: URLDispatcher

web: "[URLDispatcher](http://holyshared.github.com/URLDispatcher URLDispatcher)"

description: "Event dispatcher of simple url base."

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/URLDispatcher/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/URLDispatcher.js"
  - "Source/URLDispatcher.Resource.js"
  - "Source/URLDispatcher.Route.js"
  - "Source/URLDispatcher.Router.js"
  - "Source/URLDispatcher.Handler.js"
  - "Source/URLDispatcher.HandlerManager.js"
  - "Source/URLDispatcher.URLEventDispatcher.js"

author: holyshared

category: Utilities

tags: [utils, dispatcher, url]

current: 2.0

#docs: http://holyshared.github.com/URLDispacher/docs

demo: http://holyshared.github.com/URLDispatcher/