name: URLDispacher

web: "[URLDispacher](http://holyshared.github.com/URLDispacher URLDispacher)"

description: ""

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/URLDispacher/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/URLDispacher.js"

author: Noritaka Horio

category: Utilities

tags: [utils, dispacher, url]

current: 1.0

#docs: http://holyshared.github.com/Mixin/docs

demo: http://holyshared.github.com/URLDispacher/