name: URLDispatcher

web: "[URLDispatcher](http://holyshared.github.com/URLDispatcher URLDispatcher)"

description: "This library is an event dispatcher with a light URL base."

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/URLDispatcher/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/URLDispatcher.js"

author: holyshared

category: Utilities

tags: [utils, dispatcher, url]

current: 1.0

#docs: http://holyshared.github.com/URLDispacher/docs

demo: http://holyshared.github.com/URLDispatcher/